### PR TITLE
Fix issue #14 There is the error in displaying pages

### PR DESCRIPTION
**Pull request by yangjehpark**
After I adjusted the code...
**Test Case**
infinite == false && itemToShow.count == 2
infinite == true && itemToShow.count == 2
infinite == false && itemToShow.count >2
infinite == true && itemToShow.count > 2
**Result**
Every cases works fine.
Thanks

### CODE REVIEW

**Comment by Ewg777** [comment]
@KyoheiG3 please merge this

**Comment by KyoheiG3** [comment]
@yangjehpark Thank you for your PR.
@Ewg777 👍

**Comment by Ewg777** [comment]
@KyoheiG3 what's about updating podspec?

**Comment by KyoheiG3** [comment]
@Ewg777 I updated in [0.5.1](https://github.com/KyoheiG3/PagingView/tree/0.5.1)

**Pull request merged**
